web/login/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='login/login.html'), name='login'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render

def index(request):
    return render(request,'navbar.html')

urlpatterns = [
    path("admin/", admin.site.urls),
    path('main/',index),
    path("", include('login.urls'))
] 

web/login/models.py
from django.db import models

# Create your models here.

web/login/views.py
from django.shortcuts import render

# Create your views here.

web/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

web/templates/login/login.html
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'login:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

web/templates/navbar.html
<ul class="navbar-nav">
    <li class="nav-item ">
        <a class="nav-link" href="{% url 'login:login' %}">로그인</a>
    </li>
</ul>